 CREATE DATABASE IF NOT EXISTS Kratos;

 CREATE TABLE IF NOT EXISTS `Kratos`.`User` (
  `ID_USER` INT NOT NULL,
  `EMAIL` VARCHAR(45) NOT NULL,
  `PASSWORD` VARCHAR(45) NULL,
  `USERNAME` VARCHAR(45) NULL,
  `CREATION_DATE` DATETIME NULL,
  `LAST_LOGIN_DATE` DATETIME NULL,
  `STATE` ENUM('ACTIVE', 'INACTIVE') NULL,
  `LAST_CONNECTION_IP` VARCHAR(15) NULL,
  PRIMARY KEY (`ID_USER`),
  UNIQUE INDEX `idUser_UNIQUE` (`ID_USER` ASC) VISIBLE,
  UNIQUE INDEX `EMAIL_UNIQUE` (`EMAIL` ASC) VISIBLE)
ENGINE = InnoDB